import type { MoodWorldEffect } from "@/types/world";

export const MOOD_PRESETS: Record<string, { label: string; effect: MoodWorldEffect }> = {
  calm: {
    label: "Calm",
    effect: {
      enabled: true,
      intensity: 0.8,
      scene: { tint: "#e2ded2", tintStrength: 0.15, fogMultiplier: 0.95 },
      lighting: { intensityMultiplier: 0.95, tint: "#f5ece1", tintStrength: 0.15 },
      atmosphere: {
        starBrightnessMultiplier: 0.85,
        fireflyMultiplier: 0.7,
        cloudSpeedMultiplier: 0.6,
        cloudTint: "#ebe2d5",
        cloudTintStrength: 0.2,
        moonBrightnessMultiplier: 0.9,
        windowGlowMultiplier: 0.9,
        lampGlowMultiplier: 0.9,
      },
      environment: {
        pondTint: "#9eb5a8",
        pondTintStrength: 0.2,
        flowerBrightnessMultiplier: 0.95,
      },
      motion: { globalSpeedMultiplier: 0.75 },
    },
  },
  dreamy: {
    label: "Dreamy",
    effect: {
      enabled: true,
      intensity: 0.85,
      scene: { tint: "#d8c4e8", tintStrength: 0.25, fogMultiplier: 1.15 },
      lighting: { intensityMultiplier: 0.9, tint: "#e8d0f5", tintStrength: 0.25 },
      atmosphere: {
        starBrightnessMultiplier: 1.3,
        fireflyMultiplier: 1.5,
        cloudSpeedMultiplier: 0.8,
        cloudTint: "#dec5eb",
        cloudTintStrength: 0.35,
        moonBrightnessMultiplier: 1.25,
        windowGlowMultiplier: 1.2,
        lampGlowMultiplier: 1.15,
      },
      environment: {
        pondTint: "#9c8ab8",
        pondTintStrength: 0.3,
        flowerBrightnessMultiplier: 1.15,
      },
      motion: { globalSpeedMultiplier: 0.8 },
    },
  },
  focus: {
    label: "Focus",
    effect: {
      enabled: true,
      intensity: 0.75,
      scene: { tint: "#d4dede", tintStrength: 0.12, fogMultiplier: 0.85 },
      lighting: { intensityMultiplier: 1.08, tint: "#f0f7f7", tintStrength: 0.1 },
      atmosphere: {
        starBrightnessMultiplier: 0.9,
        fireflyMultiplier: 0.4,
        cloudSpeedMultiplier: 0.9,
        cloudTint: "#e4ecee",
        cloudTintStrength: 0.15,
        moonBrightnessMultiplier: 0.95,
        windowGlowMultiplier: 0.85,
        lampGlowMultiplier: 0.9,
      },
      environment: {
        pondTint: "#7da6a6",
        pondTintStrength: 0.2,
        flowerBrightnessMultiplier: 1.05,
      },
      motion: { globalSpeedMultiplier: 0.9 },
    },
  },
  "late-night": {
    label: "Late Night",
    effect: {
      enabled: true,
      intensity: 0.9,
      scene: { tint: "#1c1b33", tintStrength: 0.3, fogMultiplier: 1.1 },
      lighting: { intensityMultiplier: 0.8, tint: "#6b77a6", tintStrength: 0.25 },
      atmosphere: {
        starBrightnessMultiplier: 1.35,
        fireflyMultiplier: 1.6,
        cloudSpeedMultiplier: 0.7,
        cloudTint: "#22243d",
        cloudTintStrength: 0.35,
        moonBrightnessMultiplier: 1.3,
        windowGlowMultiplier: 1.6,
        lampGlowMultiplier: 1.5,
      },
      environment: {
        pondTint: "#22304d",
        pondTintStrength: 0.35,
        flowerBrightnessMultiplier: 0.85,
      },
      motion: { globalSpeedMultiplier: 0.7 },
    },
  },
  rainy: {
    label: "Rainy",
    effect: {
      enabled: true,
      intensity: 0.85,
      scene: { tint: "#7a8a99", tintStrength: 0.25, fogMultiplier: 1.3 },
      lighting: { intensityMultiplier: 0.75, tint: "#8ca0b3", tintStrength: 0.25 },
      atmosphere: {
        starBrightnessMultiplier: 0.6,
        fireflyMultiplier: 0.3,
        cloudSpeedMultiplier: 1.4,
        cloudTint: "#6e7e8c",
        cloudTintStrength: 0.3,
        moonBrightnessMultiplier: 0.7,
        windowGlowMultiplier: 1.4,
        lampGlowMultiplier: 1.3,
      },
      environment: {
        pondTint: "#556b7d",
        pondTintStrength: 0.35,
        flowerBrightnessMultiplier: 0.8,
      },
      motion: { globalSpeedMultiplier: 0.75 },
    },
  },
  happy: {
    label: "Happy",
    effect: {
      enabled: true,
      intensity: 0.85,
      scene: { tint: "#ffedd4", tintStrength: 0.18, fogMultiplier: 0.8 },
      lighting: { intensityMultiplier: 1.15, tint: "#fff3db", tintStrength: 0.2 },
      atmosphere: {
        starBrightnessMultiplier: 1.1,
        fireflyMultiplier: 1.4,
        cloudSpeedMultiplier: 1.25,
        cloudTint: "#ffeed9",
        cloudTintStrength: 0.2,
        moonBrightnessMultiplier: 1.05,
        windowGlowMultiplier: 1.1,
        lampGlowMultiplier: 1.1,
      },
      environment: {
        pondTint: "#7dbfbf",
        pondTintStrength: 0.25,
        flowerBrightnessMultiplier: 1.25,
      },
      motion: { globalSpeedMultiplier: 1.25 },
    },
  },
};

export const NEUTRAL_WORLD_EFFECT: MoodWorldEffect = {
  enabled: true,
  intensity: 0.8,
  scene: { tint: undefined, tintStrength: 0.2, fogMultiplier: 1.0 },
  lighting: { intensityMultiplier: 1.0, tint: undefined, tintStrength: 0.2 },
  atmosphere: {
    starBrightnessMultiplier: 1.0,
    fireflyMultiplier: 1.0,
    cloudSpeedMultiplier: 1.0,
    cloudTint: undefined,
    cloudTintStrength: 0.25,
    moonBrightnessMultiplier: 1.0,
    windowGlowMultiplier: 1.0,
    lampGlowMultiplier: 1.0,
  },
  environment: {
    pondTint: undefined,
    pondTintStrength: 0.3,
    flowerBrightnessMultiplier: 1.0,
  },
  motion: { globalSpeedMultiplier: 1.0 },
};
