export const defaultCollectibles = [
  {
    name: 'Little Star',
    slug: 'little-star',
    description: 'A tiny celestial fragment that fell from the night sky, still holding a gentle glimmer.',
    hint: 'Where the water softly catches the sky.',
    category: 'STAR',
    rarity: 'COMMON',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 0,
    model: {
      modelKey: 'tiny_star',
      scalePreset: 'NORMAL',
      rotationPreset: 'DEFAULT',
    },
    appearance: {
      glowColor: '#ffe8b2',
      accentColor: '#f7d070',
      idleAnimation: 'FLOAT',
      revealEffect: 'TINY_STARS',
    },
    placement: {
      anchor: 'POND_EDGE',
      offset: { x: 0.15, y: 0.05, z: 0.2 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default starter collectible near pond edge',
  },
  {
    name: 'Pressed Wildflower',
    slug: 'pressed-flower',
    description: 'A delicate meadow petal kept safe between pages of a sketchbook.',
    hint: 'Resting quietly amidst the wild grass.',
    category: 'FLOWER',
    rarity: 'COMMON',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 1,
    model: {
      modelKey: 'pressed_flower',
      scalePreset: 'NORMAL',
      rotationPreset: 'UPRIGHT',
    },
    appearance: {
      glowColor: '#ffd4dc',
      accentColor: '#e8899e',
      idleAnimation: 'FLOAT',
      revealEffect: 'PETALS',
    },
    placement: {
      anchor: 'FLOWER_FIELD',
      offset: { x: -0.2, y: 0.04, z: 0.1 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default flower collectible in flower field',
  },
  {
    name: 'Tiny Detail Brush',
    slug: 'tiny-brush',
    description: 'An artist\'s slender wooden brush tipped with dried lavender pigment.',
    hint: 'Left beside where ideas take form in color.',
    category: 'ART',
    rarity: 'COMMON',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 2,
    model: {
      modelKey: 'paint_brush',
      scalePreset: 'NORMAL',
      rotationPreset: 'TILTED',
    },
    appearance: {
      glowColor: '#e0d2fc',
      accentColor: '#a682e6',
      idleAnimation: 'FLOAT',
      revealEffect: 'SPARKLE',
    },
    placement: {
      anchor: 'ART_WALL',
      offset: { x: 0.25, y: 0.05, z: 0.15 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default art brush collectible near easel',
  },
  {
    name: 'Paper Crane',
    slug: 'paper-crane',
    description: 'An origami crane folded from textured parchment paper, carrying an unwritten wish.',
    hint: 'Perched where one sits to watch the quiet horizon.',
    category: 'MEMORY',
    rarity: 'COMMON',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 3,
    model: {
      modelKey: 'paper_crane',
      scalePreset: 'NORMAL',
      rotationPreset: 'DEFAULT',
    },
    appearance: {
      glowColor: '#fff2db',
      accentColor: '#d6b885',
      idleAnimation: 'FLOAT',
      revealEffect: 'SPARKLE',
    },
    placement: {
      anchor: 'BENCH',
      offset: { x: -0.15, y: 0.08, z: 0.05 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default paper crane collectible on island bench',
  },
  {
    name: 'Faded Polaroid',
    slug: 'polaroid',
    description: 'A miniature square instant photograph capturing a golden sunset over the cottage.',
    hint: 'Sheltered close to the cottage blossoms.',
    category: 'MEMORY',
    rarity: 'SPECIAL',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 4,
    model: {
      modelKey: 'polaroid',
      scalePreset: 'NORMAL',
      rotationPreset: 'UPRIGHT',
    },
    appearance: {
      glowColor: '#ffe5cf',
      accentColor: '#e39f78',
      idleAnimation: 'FLOAT',
      revealEffect: 'GLOW',
    },
    placement: {
      anchor: 'HOUSE_GARDEN',
      offset: { x: 0.2, y: 0.06, z: 0.15 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default instant photograph collectible in cottage garden',
  },
  {
    name: 'Moon Charm',
    slug: 'moon-charm',
    description: 'A silver crescent amulet that glows faintly with the soft luminescence of dusk.',
    hint: 'Lying where the wooden planks cross the water.',
    category: 'MAGIC',
    rarity: 'SPECIAL',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 5,
    model: {
      modelKey: 'moon_charm',
      scalePreset: 'NORMAL',
      rotationPreset: 'DEFAULT',
    },
    appearance: {
      glowColor: '#d8eaf7',
      accentColor: '#88b5dc',
      idleAnimation: 'SLOW_SPIN',
      revealEffect: 'SOFT_PULSE',
    },
    placement: {
      anchor: 'BRIDGE',
      offset: { x: 0.1, y: 0.06, z: -0.15 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default moon charm collectible near bridge',
  },
  {
    name: 'Bronze Music Note',
    slug: 'music-note',
    description: 'A miniature eighth-note sculpted from antique brass, humming with a quiet melody.',
    hint: 'Resting near the gentle turn of spinning vinyl.',
    category: 'MUSIC',
    rarity: 'COMMON',
    source: 'WORLD',
    enabled: true,
    isPublished: true,
    order: 6,
    model: {
      modelKey: 'music_note',
      scalePreset: 'NORMAL',
      rotationPreset: 'UPRIGHT',
    },
    appearance: {
      glowColor: '#f5deb3',
      accentColor: '#c99e63',
      idleAnimation: 'FLOAT',
      revealEffect: 'SPARKLE',
    },
    placement: {
      anchor: 'CLOCK_AREA',
      offset: { x: -0.2, y: 0.06, z: 0.15 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Default music note collectible near record player',
  },
  {
    name: 'Golden Wing',
    slug: 'golden-wing',
    description: 'An ethereal gossamer butterfly wing inscribed with golden starlight. A gift from noticing what others overlook.',
    hint: 'Awarded to those who greet the winged visitor more than once.',
    category: 'MAGIC',
    rarity: 'RARE',
    source: 'SECRET', // SECRET ONLY - Never placed as physical world pickup
    enabled: true,
    isPublished: true,
    order: 7,
    model: {
      modelKey: 'golden_wing',
      scalePreset: 'FEATURED',
      rotationPreset: 'UPRIGHT',
    },
    appearance: {
      glowColor: '#ffe082',
      accentColor: '#ffb300',
      idleAnimation: 'SLOW_SPIN',
      revealEffect: 'GLOW',
    },
    placement: {
      anchor: 'FLOWER_FIELD',
      offset: { x: 0, y: 0, z: 0 },
      visibleInPeriods: [],
      requiredMood: null,
    },
    behavior: {
      hideAfterCollected: true,
    },
    adminNote: 'Awarded strictly via the Butterfly Secret (Phase 8 Secret integration)',
  },
];

