export const defaultContent = {
  site: {
    title: "Shaivi's Little World",
    description: "A small world for big ideas. Explore a playful, handcrafted creative portfolio.",
    wordmark: "s✳",
    introHeading: "Shaivi's little world.",
    introSubtext: "Welcome to Shaivi's little world.",
    introDescription: "A place for ideas, daydreams, and everything in between.",
    exploreLabel: "Explore",
    sectionLabels: { ABOUT: 'Artist', QUOTES: 'Read quotes', GALLERY: 'Open art', JOURNEY: 'Look through', CONTACT: 'Post a letter', MUSIC: 'Play music' },
    footerWorldText: "Follow your curiosity.",
    footerExploreText: "A little closer.",
    footerWorldInstruction: "Tap an object to explore · drag to look around",
    footerExploreInstruction: "Take your time. There's more to discover.",
    discoveryLabel: "little discoveries",
    secretMessages: ["Sample fact: my best ideas arrive at inconvenient times.", "Sample fact: every notebook deserves another notebook."],
    socialLinks: [],
    accentColor: "#987b68",
    isPublished: true
  },
  artist: {
    name: "Shaivi",
    label: "Creative Mind & Maker",
    caption: "A glimpse into my creative process.",
    bio: "I believe in building small, beautiful things that bring a little more magic into the world.",
    portrait: { url: "https://res.cloudinary.com/demo/image/upload/sample.jpg" },
    smallImage: { url: "https://res.cloudinary.com/demo/image/upload/sample.jpg" },
    annotationText: "Just thinking out loud.",
    tags: ["Design", "Art", "Code"],
    details: [{ label: "Based in", value: "Earth" }],
    note: "Always exploring.",
    sectionHeading: "Meet the Artist",
    sectionKicker: "Who is behind this?",
    isPublished: true
  },
  quotes: Array.from({ length: 8 }, (_, i) => ({
    text: `This is sample quote number ${i + 1}. Creativity is intelligence having fun.`,
    category: `Category ${i % 3}`,
    order: i,
    isPublished: true
  })),
  artworks: Array.from({ length: 12 }, (_, i) => ({
    title: `Artwork ${i + 1}`,
    year: `202${i % 4}`,
    caption: `Sample caption for artwork ${i + 1}.`,
    altText: `Alt text for artwork ${i + 1}`,
    source: "Original",
    credit: "Shaivi",
    image: { url: "https://res.cloudinary.com/demo/image/upload/sample.jpg" },
    order: i,
    isPublished: true,
    initialPosition: { x: Math.random() * 800, y: Math.random() * 600 },
    rotation: Math.random() * 20 - 10,
    scale: 1.0
  })),
  journey: [
    {
      title: "First Sketches",
      year: "2022",
      text: "An imagined beginning: a pencil, a blank page, and a growing collection of little observations.",
      image: { url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80" },
      altText: "First Sketches",
      order: 0,
      isPublished: true,
      desktopPosition: { x: 8, y: 65 }
    },
    {
      title: "Experiments",
      year: "2023",
      text: "Trying unfamiliar colours and finding the unexpected in happy accidents.",
      image: { url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80" },
      altText: "Experiments",
      order: 1,
      isPublished: true,
      desktopPosition: { x: 29, y: 21 }
    },
    {
      title: "Digital Art",
      year: "2024",
      text: "Taking the same curiosity into a new medium. Learning to make room for play.",
      image: { url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80" },
      altText: "Digital Art",
      order: 2,
      isPublished: true,
      desktopPosition: { x: 48, y: 62 }
    },
    {
      title: "Visual Stories",
      year: "2025",
      text: "Connecting individual ideas into small narratives, one image at a time.",
      image: { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80" },
      altText: "Visual Stories",
      order: 3,
      isPublished: true,
      desktopPosition: { x: 69, y: 15 }
    },
    {
      title: "Exploring Now",
      year: "2026",
      text: "Still collecting, still noticing. The next constellation has yet to take shape.",
      image: { url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
      altText: "Exploring Now",
      order: 4,
      isPublished: true,
      desktopPosition: { x: 91, y: 48 }
    }
  ],
  songs: Array.from({ length: 7 }, (_, i) => ({
    title: `Song ${i + 1}`,
    artist: "Demo Artist",
    duration: 180 + i * 10,
    cover: { url: "https://res.cloudinary.com/demo/image/upload/sample.jpg" },
    order: i,
    isPublished: true
  })),
  moods: [
    {
      name: "Calm",
      slug: "calm",
      paperColor: "#d7ddc5",
      inkColor: "#354537",
      order: 0,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.85,
        scene: {
          tint: "#c7d6c5",
          tintStrength: 0.15,
          fogMultiplier: 1.08,
        },
        lighting: {
          intensityMultiplier: 0.9,
          tint: "#e5ece0",
          tintStrength: 0.1,
        },
        atmosphere: {
          starBrightnessMultiplier: 1.0,
          fireflyMultiplier: 0.8,
          cloudSpeedMultiplier: 0.75,
          cloudTint: "#e5ece0",
          cloudTintStrength: 0.1,
          moonBrightnessMultiplier: 0.95,
          windowGlowMultiplier: 1.05,
          lampGlowMultiplier: 1.0,
        },
        environment: {
          pondTint: "#7ea396",
          pondTintStrength: 0.15,
          flowerBrightnessMultiplier: 0.95,
        },
        motion: {
          globalSpeedMultiplier: 0.75,
        },
      },
    },
    {
      name: "Dreamy",
      slug: "dreamy",
      paperColor: "#c9c5df",
      inkColor: "#474059",
      order: 1,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.9,
        scene: {
          tint: "#b99be8",
          tintStrength: 0.25,
          fogMultiplier: 1.15,
        },
        lighting: {
          intensityMultiplier: 0.88,
          tint: "#c7b4e9",
          tintStrength: 0.2,
        },
        atmosphere: {
          starBrightnessMultiplier: 1.25,
          fireflyMultiplier: 1.35,
          cloudSpeedMultiplier: 0.7,
          cloudTint: "#baa4df",
          cloudTintStrength: 0.2,
          moonBrightnessMultiplier: 1.15,
          windowGlowMultiplier: 1.15,
          lampGlowMultiplier: 1.1,
        },
        environment: {
          pondTint: "#8f87bb",
          pondTintStrength: 0.25,
          flowerBrightnessMultiplier: 1.0,
        },
        motion: {
          globalSpeedMultiplier: 0.75,
        },
      },
    },
    {
      name: "Focus",
      slug: "focus",
      paperColor: "#d8ceba",
      inkColor: "#474334",
      order: 2,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.8,
        scene: {
          tint: "#d6cfc5",
          tintStrength: 0.1,
          fogMultiplier: 0.8,
        },
        lighting: {
          intensityMultiplier: 1.0,
          tint: "#f0ede8",
          tintStrength: 0.05,
        },
        atmosphere: {
          starBrightnessMultiplier: 0.6,
          fireflyMultiplier: 0.35,
          cloudSpeedMultiplier: 0.6,
          cloudTint: "#eae6df",
          cloudTintStrength: 0.05,
          moonBrightnessMultiplier: 0.9,
          windowGlowMultiplier: 0.95,
          lampGlowMultiplier: 0.95,
        },
        environment: {
          pondTint: "#7a9e9a",
          pondTintStrength: 0.1,
          flowerBrightnessMultiplier: 0.85,
        },
        motion: {
          globalSpeedMultiplier: 0.7,
        },
      },
    },
    {
      name: "Late Night",
      slug: "late-night",
      paperColor: "#343341",
      inkColor: "#e7ddce",
      order: 3,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.95,
        scene: {
          tint: "#262b45",
          tintStrength: 0.22,
          fogMultiplier: 1.1,
        },
        lighting: {
          intensityMultiplier: 0.8,
          tint: "#444b70",
          tintStrength: 0.2,
        },
        atmosphere: {
          starBrightnessMultiplier: 1.45,
          fireflyMultiplier: 1.4,
          cloudSpeedMultiplier: 0.65,
          cloudTint: "#2c3352",
          cloudTintStrength: 0.25,
          moonBrightnessMultiplier: 1.3,
          windowGlowMultiplier: 1.4,
          lampGlowMultiplier: 1.35,
        },
        environment: {
          pondTint: "#3b4563",
          pondTintStrength: 0.3,
          flowerBrightnessMultiplier: 0.8,
        },
        motion: {
          globalSpeedMultiplier: 0.7,
        },
      },
    },
    {
      name: "Rainy",
      slug: "rainy",
      paperColor: "#bccbd0",
      inkColor: "#354954",
      order: 4,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.85,
        scene: {
          tint: "#788796",
          tintStrength: 0.25,
          fogMultiplier: 1.25,
        },
        lighting: {
          intensityMultiplier: 0.8,
          tint: "#8292a0",
          tintStrength: 0.18,
        },
        atmosphere: {
          starBrightnessMultiplier: 0.5,
          fireflyMultiplier: 0.6,
          cloudSpeedMultiplier: 0.85,
          cloudTint: "#6e7e8c",
          cloudTintStrength: 0.25,
          moonBrightnessMultiplier: 0.8,
          windowGlowMultiplier: 1.15,
          lampGlowMultiplier: 1.1,
        },
        environment: {
          pondTint: "#576f7a",
          pondTintStrength: 0.3,
          flowerBrightnessMultiplier: 0.8,
        },
        motion: {
          globalSpeedMultiplier: 0.75,
        },
      },
    },
    {
      name: "Happy",
      slug: "happy",
      paperColor: "#e8d09b",
      inkColor: "#624b35",
      order: 5,
      isPublished: true,
      worldEffect: {
        enabled: true,
        intensity: 0.9,
        scene: {
          tint: "#f5df98",
          tintStrength: 0.18,
          fogMultiplier: 0.9,
        },
        lighting: {
          intensityMultiplier: 1.12,
          tint: "#fae8b4",
          tintStrength: 0.15,
        },
        atmosphere: {
          starBrightnessMultiplier: 0.9,
          fireflyMultiplier: 1.25,
          cloudSpeedMultiplier: 1.05,
          cloudTint: "#f7ebc6",
          cloudTintStrength: 0.15,
          moonBrightnessMultiplier: 1.05,
          windowGlowMultiplier: 1.1,
          lampGlowMultiplier: 1.05,
        },
        environment: {
          pondTint: "#68a8aa",
          pondTintStrength: 0.15,
          flowerBrightnessMultiplier: 1.15,
        },
        motion: {
          globalSpeedMultiplier: 1.1,
        },
      },
    },
  ],
  contact: {
    heading: "Say Hello",
    intro: "Leave a little note behind.",
    handwrittenNote: "some things are better\nwritten down.",
    fieldLabels: { name: "Your name", email: "Your email", message: "Your little note" },
    buttonText: "Send Message",
    successMessage: "Thank you for your note! I'll read it soon.",
    disclaimer: "Your email is kept private.",
    signoff: "With a little curiosity,",
    email: "hello@example.com",
    isPublished: true
  }
};

