export const defaultSecrets = [
  {
    name: 'Butterfly Whisper',
    slug: 'butterfly-whisper',
    enabled: true,
    isPublished: true,
    order: 0,
    target: {
      type: 'BUTTERFLY',
      id: 'golden-butterfly',
    },
    trigger: {
      type: 'MULTI_CLICK',
      requiredCount: 3,
      windowMs: 12000,
    },
    conditions: {},
    reveal: {
      type: 'MESSAGE',
      title: '✦ Enchanted Discovery ✦',
      message: 'You caught the golden butterfly! A fleeting whisper from Shaivi’s field guide.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'SPARKLE',
    },
    behavior: {
      repeatable: true,
      cooldownMs: 15000,
      oncePerSession: false,
    },
    adminNote: 'Default migratory butterfly whisper secret',
  },
  {
    name: 'Enchanted Flying Manuscript',
    slug: 'flying-paper',
    enabled: true,
    isPublished: true,
    order: 1,
    target: {
      type: 'FLYING_PAGE',
      id: 'flying-paper',
    },
    trigger: {
      type: 'MULTI_CLICK',
      requiredCount: 3,
      windowMs: 12000,
    },
    conditions: {},
    reveal: {
      type: 'MESSAGE',
      title: '✦ The Wandering Manuscript ✦',
      message:
        'You caught the enchanted flying page! It carries a gentle message written in gold ink: "Some stories refuse to stay bound in books—they take flight across the open sky."',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'PETALS',
    },
    behavior: {
      repeatable: true,
      cooldownMs: 15000,
      oncePerSession: false,
    },
    adminNote: 'Enchanted flying parchment page soaring around the island',
  },
  {
    name: 'Pond Star Ripple',
    slug: 'pond-star',
    enabled: true,
    isPublished: true,
    order: 1,
    target: {
      type: 'POND',
      id: 'main-pond',
    },
    trigger: {
      type: 'RIPPLE',
      requiredCount: 5,
      windowMs: 15000,
    },
    conditions: {},
    reveal: {
      type: 'MESSAGE',
      title: '✧ Reflection Beneath the Ripples ✧',
      message: 'Five ripples disturbed the calm water, revealing a glowing secret under the stones.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'GLOW',
    },
    behavior: {
      repeatable: false,
    },
    adminNote: 'Triggered by 5 ripples in the pond',
  },
  {
    name: 'Night Window Secret',
    slug: 'night-window',
    enabled: true,
    isPublished: true,
    order: 2,
    target: {
      type: 'HOUSE_WINDOW',
      id: 'front-window',
    },
    trigger: {
      type: 'CLICK',
      requiredCount: 1,
    },
    conditions: {
      timeOfDay: ['NIGHT'],
    },
    reveal: {
      type: 'MESSAGE',
      title: '☽ Midnight Studio Warmth ☽',
      message: 'The lights stay on late in the studio. Ideas glow brightest when the rest of the island sleeps.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'SOFT_PULSE',
    },
    behavior: {
      repeatable: true,
      cooldownMs: 10000,
    },
    adminNote: 'Window secret, unlocks only at night',
  },
  {
    name: 'Lamp Mystery',
    slug: 'lamp-mystery',
    enabled: true,
    isPublished: true,
    order: 3,
    target: {
      type: 'LAMP',
      id: 'main-lamp',
    },
    trigger: {
      type: 'TOGGLE',
      requiredCount: 4,
      windowMs: 15000,
    },
    conditions: {},
    reveal: {
      type: 'MESSAGE',
      title: '☀ Lantern Keepers ☀',
      message: 'Clicking the lamp repeatedly stirs ancient moth-motes into the evening air.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'TINY_STARS',
    },
    behavior: {
      repeatable: true,
      cooldownMs: 10000,
    },
    adminNote: 'Four lamp toggles within 15 seconds',
  },
  {
    name: 'Tree Blossom Drop',
    slug: 'tree-whisper',
    enabled: true,
    isPublished: true,
    order: 4,
    target: {
      type: 'TREE',
      id: 'island-tree',
    },
    trigger: {
      type: 'SHAKE',
      requiredCount: 3,
      windowMs: 10000,
    },
    conditions: {},
    reveal: {
      type: 'MESSAGE',
      title: '🍂 Fallen Acorn Memory 🍂',
      message: 'The pine branches rustled and shared a little daydream with you.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'PETALS',
    },
    behavior: {
      repeatable: true,
      cooldownMs: 10000,
    },
    adminNote: 'Shaking trees 3 times triggers petals',
  },
  {
    name: 'Letter Traveler',
    slug: 'post-office-surprise',
    enabled: true,
    isPublished: true,
    order: 5,
    target: {
      type: 'MAILBOX',
      id: 'contact-mailbox',
    },
    trigger: {
      type: 'LETTER_SENT',
      requiredCount: 1,
    },
    conditions: {
      letterSent: true,
    },
    reveal: {
      type: 'MESSAGE',
      title: '✉ Postcard Delivered! ✉',
      message: 'Your letter folded itself into the wind and is on its journey to Shaivi’s desk.',
      position: 'center',
      duration: 'NORMAL',
      visualEffect: 'TINY_STARS',
    },
    behavior: {
      repeatable: false,
    },
    adminNote: 'Unlocks after real letter submission',
  },
];

