export const defaultWorldSettings = {
  schemaVersion: 2,
  identity: {
    worldTitle: "Shaivi's Little World",
    wordmark: "s✳",
    exploreLabel: "Explore",
    instructionText: "Tap an object to explore · drag to look around",
    discoveryLabel: "little discoveries",
    secretMessage: "A tiny secret, found.",
  },
  intro: {
    enabled: true,
    eyebrow: "YOU’RE ALWAYS WELCOME HERE",
    heading: "Shaivi’s little world.",
    body: "A place for ideas, daydreams, and everything in between.",
    enterButtonLabel: "Skip intro →",
    starEnabled: true,
  },
  scene: {
    backgroundColor: "#d5cbdc",
    fog: {
      enabled: true,
      color: "#d5cbdc",
      near: 28,
      far: 65,
    },
  },
  lighting: {
    hemisphere: {
      enabled: true,
      skyColor: "#fff3d7",
      groundColor: "#9b91b1",
      intensity: 2.0,
    },
    directional: {
      enabled: true,
      color: "#ffffff",
      intensity: 3.0,
      position: { x: -5, y: 10, z: 6 },
      castShadow: true,
    },
    shadowLevel: "BALANCED",
  },
  island: {
    terrainColor: "#9b7f78",
    grassEdgeColor: "#bbc79c",
    grassTopColor: "#c6cfab",
    steppingStonesColor: "#eaddc5",
    steppingStonesVisible: true,
    benchVisible: true,
    benchWoodColor: "#b39273",
    benchLegsColor: "#876850",
    flowers: {
      enabled: true,
      density: "MEDIUM",
      primaryColor: "#f4dbac",
      secondaryColor: "#df9ca5",
    },
    trees: {
      enabled: true,
      swayEnabled: true,
      swayStrength: 0.012,
      trunkColor: "#867055",
      leavesColor: "#9ca97a",
    },
    pond: {
      enabled: true,
      waterColor: "#89b9b9",
      stonesColor: "#d6cbbb",
      rippleEnabled: true,
      rippleColor: "#edf4e7",
    },
  },
  environment: {
    clouds: {
      enabled: true,
      color: "#f1e7ed",
      motionEnabled: true,
      speed: 1.0,
    },
    details: {
      lampEnabled: true,
      lampDefaultLit: true,
      lampPostColor: "#657058",
      lampGlowColor: "#f7dfa0",
      bridgeVisible: true,
      bridgeColor: "#b69a76",
      mugSteamEnabled: true,
      motesEnabled: true,
      motesAmount: "FULL",
      motesColor: "#ffeab5",
      booksVisible: true,
    },
  },
  motion: {
    islandFloatEnabled: true,
    islandFloatStrength: 0.07,
    islandFloatSpeed: 0.5,
    islandRotationDrift: 0.01,
  },
  objects: {
    house: {
      visible: true,
      wallColor: "#e9cfaa",
      roofColor: "#b46d57",
      doorColor: "#75877a",
      windowGlowEnabled: true,
      windowGlowColor: "#f7ddb0",
      windowGlowIntensity: 0.35,
      chimneySmokeEnabled: true,
      plantsEnabled: true,
    },
    desk: {
      visible: true,
      woodColor: "#b89372",
      frameColor: "#4a5555",
      screenInactiveColor: "#a7b8b3",
      screenActiveColor: "#efe9df",
    },
    artWall: {
      visible: true,
      frameColor: "#a88364",
      canvasColor: "#f2d9b8",
      easelColor: "#967655",
    },
    telescope: {
      visible: true,
      bodyColor: "#ede0bb",
      standColor: "#9b7f61",
      accentColor: "#556478",
    },
    mailbox: {
      visible: true,
      bodyColor: "#b67469",
      postColor: "#967857",
      flagColor: "#e8c886",
    },
    clock: {
      visible: true,
      bodyColor: "#ac876a",
      faceColor: "#f0ddb6",
      handColor: "#596555",
    },
  },
  interactions: {
    hoverScale: "NORMAL",
    treeShakeEnabled: true,
    treeShakeStrength: "NORMAL",
    butterflySecret: {
      enabled: true,
      requiredClicks: 3,
      butterflyColor: "#f9d092",
    },
  },
  camera: {
    travelSpeed: "NORMAL",
    easing: "SMOOTH",
    arcStrength: "NORMAL",
    orbitEnabled: true,
    orbitSpeed: 0.3,
    framing: "BALANCED",
  },
  ambience: {
    soundEnabled: true,
    defaultVolume: 70,
  },
  sections: {
    ABOUT: {
      enabled: true,
      label: "Artist",
      icon: "⌂",
    },
    QUOTES: {
      enabled: true,
      label: "Quotes",
      icon: "✳",
    },
    GALLERY: {
      enabled: true,
      label: "Art Gallery",
      icon: "▧",
    },
    JOURNEY: {
      enabled: true,
      label: "Star Journey",
      icon: "✧",
    },
    CONTACT: {
      enabled: true,
      label: "Post a Letter",
      icon: "✉",
    },
    MUSIC: {
      enabled: true,
      label: "Music & Moods",
      icon: "♫",
    },
  },
  dayNight: {
    enabled: true,
    mode: "automatic",
    timeSource: "visitor-local",
    fixedTimezone: "Asia/Kolkata",
    fixedPeriod: "DAY",
    defaultPeriod: "DAY",
    allowVisitorOverride: true,
    transition: {
      enabled: true,
      durationSeconds: 6,
    },
    schedule: {
      morningStart: "05:30",
      dayStart: "08:00",
      sunsetStart: "17:00",
      nightStart: "19:00",
    },
    profiles: {
      morning: {
        backgroundColor: "#dcd6e8",
        fog: {
          enabled: true,
          color: "#dcd6e8",
          near: 26,
          far: 62,
        },
        hemisphere: {
          enabled: true,
          skyColor: "#fcecd2",
          groundColor: "#9389a6",
          intensity: 2.1,
        },
        directional: {
          enabled: true,
          color: "#ffeec9",
          intensity: 2.6,
          position: { x: -6, y: 8, z: 6 },
        },
        windowGlowMultiplier: 0.35,
        lampDefaultLit: false,
        stars: {
          enabled: false,
          density: "OFF",
          brightness: 0.3,
          twinkle: false,
        },
        moon: {
          enabled: false,
          color: "#f8f4e6",
          brightness: 0.4,
          size: "NORMAL",
        },
        firefliesMultiplier: 0.3,
        cloudTint: "#f5ecf0",
        pondTint: "#96c4c4",
        ambienceMultiplier: 0.85,
      },
      day: {
        backgroundColor: "#d5cbdc",
        fog: {
          enabled: true,
          color: "#d5cbdc",
          near: 28,
          far: 65,
        },
        hemisphere: {
          enabled: true,
          skyColor: "#fff3d7",
          groundColor: "#9b91b1",
          intensity: 2.0,
        },
        directional: {
          enabled: true,
          color: "#ffffff",
          intensity: 3.0,
          position: { x: -5, y: 10, z: 6 },
        },
        windowGlowMultiplier: 0.15,
        lampDefaultLit: false,
        stars: {
          enabled: false,
          density: "OFF",
          brightness: 0,
          twinkle: false,
        },
        moon: {
          enabled: false,
          color: "#ffffff",
          brightness: 0,
          size: "NORMAL",
        },
        firefliesMultiplier: 0.1,
        cloudTint: "#f1e7ed",
        pondTint: "#89b9b9",
        ambienceMultiplier: 1.0,
      },
      sunset: {
        backgroundColor: "#dfbfc0",
        fog: {
          enabled: true,
          color: "#dfbfc0",
          near: 24,
          far: 58,
        },
        hemisphere: {
          enabled: true,
          skyColor: "#ffd1a4",
          groundColor: "#7d627c",
          intensity: 2.3,
        },
        directional: {
          enabled: true,
          color: "#ff9d6c",
          intensity: 2.8,
          position: { x: 7, y: 5, z: 5 },
        },
        windowGlowMultiplier: 0.85,
        lampDefaultLit: true,
        stars: {
          enabled: true,
          density: "SPARSE",
          brightness: 0.6,
          twinkle: true,
        },
        moon: {
          enabled: false,
          color: "#f9f1de",
          brightness: 0.5,
          size: "NORMAL",
        },
        firefliesMultiplier: 0.75,
        cloudTint: "#ecc8bf",
        pondTint: "#c29294",
        ambienceMultiplier: 0.85,
      },
      night: {
        backgroundColor: "#1b1e2e",
        fog: {
          enabled: true,
          color: "#212538",
          near: 22,
          far: 55,
        },
        hemisphere: {
          enabled: true,
          skyColor: "#4f5c88",
          groundColor: "#222538",
          intensity: 2.0,
        },
        directional: {
          enabled: true,
          color: "#b6d4f8",
          intensity: 2.4,
          position: { x: -5, y: 10, z: 6 },
        },
        windowGlowMultiplier: 1.7,
        lampDefaultLit: true,
        stars: {
          enabled: true,
          density: "FULL",
          brightness: 1.0,
          twinkle: true,
        },
        moon: {
          enabled: true,
          color: "#e8f0fc",
          brightness: 1.0,
          size: "NORMAL",
        },
        firefliesMultiplier: 1.4,
        cloudTint: "#555d78",
        pondTint: "#2b394e",
        ambienceMultiplier: 0.65,
      },
    },
  },
  musicMood: {
    enabled: true,
    transitionDuration: 2.5,
  },
  completion: {
    enabled: true,
    autoPlayEnabled: true,
    autoPlayOnce: true,
    eyebrow: "you found your way through this little world ✦",
    title: "some things were meant to be noticed slowly.",
    message: "A quiet thank you for wandering through Shaivi’s Little World.",
    buttonLabel: "Continue exploring",
    replayLabel: "Replay final moment ✦",
    optionalChime: false,
  },
};

